import { StyleSheet } from 'react-native';
import { fonts } from '../constants/fonts';

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        padding: 20,
        backgroundColor: '#fff',
        position: 'relative',
        overflow: 'hidden',
    },
    auraBallTopRight: {
        position: 'absolute',
        top: -250,
        right: -250,
        width: 500,
        height: 500,
    },
    auraBallBottomLeft: {
        position: 'absolute',
        bottom: -250,
        left: -250,
        width: 500,
        height: 500,
    },
    contentBox: {
        width: '100%',
        maxWidth: 400,
        zIndex: 1,
        flex: 1,
        justifyContent: 'space-between',
        position: 'relative',
    },
    progressContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: 10,
        width: '100%',
        paddingHorizontal: 20,
    },
    progressBar: {
        flex: 1,
        height: 20,
        backgroundColor: '#F5F5F5',
        borderRadius: 10,
        borderWidth: 2,
        borderColor: '#252525',
        overflow: 'hidden',
        marginRight: 8,
    },
    progressFill: {
        height: '100%',
        backgroundColor: '#526EFF',
        borderRadius: 8,
    },
    progressText: {
        fontSize: 20,
        fontFamily: fonts.bold,
        color: '#666',
        textAlign: 'right',
        textTransform: 'lowercase',
        minWidth: 45,
    },
    // Weight plates progress animation styles
    weightPlatesContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: 10,
        width: '100%',
        paddingHorizontal: 20,
    },
    weightPlatesRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        flexWrap: 'nowrap',
        gap: 4,
    },
    weightPlate: {
        width: 20,
        height: 20,
        borderRadius: 10,
        borderWidth: 2.5,
        borderColor: '#252525',
        backgroundColor: '#F5F5F5', // Light gray fill for unfilled circles
    },
    weightPlateFilled: {
        backgroundColor: '#526EFF',
        borderColor: '#252525',
    },
    scrollView: {
        flex: 1,
        width: '100%',
    },
    scrollContent: {
        flexGrow: 1,
        justifyContent: 'center',
        alignItems: 'center',
        paddingBottom: 20,
        paddingTop: 60, // Space for back button
        minHeight: '100%',
    },
    stepContent: {
        width: '100%',
        alignItems: 'center',
        justifyContent: 'center',
        paddingHorizontal: 20,
    },
    welcomeLogo: {
        width: 350,
        height: 60,
        marginTop: 10,
        alignSelf: 'center',
    },
    welcomeTitle: {
        fontSize: 36,
        fontFamily: fonts.regular,
        color: '#252525',
        textAlign: 'center',
        marginBottom: 0,
        textTransform: 'lowercase',
    },
    stepTitle: {
        fontSize: 32,
        fontFamily: fonts.bold,
        color: '#252525',
        textAlign: 'center',
        marginBottom: 8,
        textTransform: 'lowercase',
    },
    stepSubtitle: {
        fontSize: 16,
        fontFamily: fonts.regular,
        color: '#ADADAD',
        textAlign: 'center',
        marginBottom: 30,
        textTransform: 'lowercase',
    },
    usernameErrorText: {
        color: '#FF5151',
        fontSize: 18,
        fontFamily: fonts.regular,
        marginTop: 8,
        textAlign: 'center',
    },
    usernameSuccessText: {
        color: '#26F170',
        fontSize: 18,
        fontFamily: fonts.regular,
        marginTop: 8,
        textAlign: 'center',
    },
    usernameStatusText: {
        color: '#666',
        fontSize: 14,
        fontFamily: fonts.regular,
        marginTop: 8,
        textAlign: 'center',
    },
    inputWrapper: {
        width: 360,
        alignSelf: 'center',
    },
    usernameInputContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        borderWidth: 2,
        borderColor: '#252525',
        borderRadius: 10,
        backgroundColor: '#F5F5F5',
        paddingHorizontal: 15,
        minHeight: 50,
    },
    usernamePrefix: {
        fontSize: 18,
        fontFamily: fonts.regular,
        color: '#666',
        marginRight: 4,
    },
    usernameInput: {
        flex: 1,
        fontSize: 18,
        fontFamily: fonts.regular,
        color: '#252525',
        backgroundColor: 'transparent',
        borderWidth: 0,
        paddingVertical: 0,
        paddingHorizontal: 0,
        height: '100%',
    },
    agePickerContainer: {
        alignItems: 'center',
        justifyContent: 'center',
        marginTop: 0,
        marginBottom: 20,
        height: 240, // Match mask height for 3 items
        position: 'relative',
        width: '100%',
    },
    agePickerMask: {
        height: 240, // 3 items * 80px = 240px
        width: '100%',
        overflow: 'hidden',
        alignItems: 'center',
        justifyContent: 'center',
    },
    ageScrollIndicator: {
        position: 'absolute',
        left: 0,
        right: 0,
        top: '50%',
        transform: [{ translateY: -1 }],
        alignItems: 'center',
        zIndex: 1,
        pointerEvents: 'none',
    },
    ageScrollLine: {
        width: 200,
        height: 2,
        backgroundColor: '#E0E0E0',
    },
    ageScrollView: {
        width: '100%',
        height: 240, // Match mask height to show 3 items
    },
    ageScrollContent: {
        alignItems: 'center',
    },
    ageItem: {
        width: '100%',
        alignItems: 'center',
        justifyContent: 'center',
    },
    ageItemSelected: {
        // Selected item styling
    },
    agePickerTextBase: {
        fontFamily: fonts.bold,
        textAlign: 'center',
    },
    agePickerTextSelected: {
        fontSize: 96,
        fontFamily: fonts.bold,
        color: '#526EFF',
        textAlign: 'center',
    },
    agePickerNumberSecondary: {
        fontSize: 40,
        fontFamily: fonts.regular,
        color: '#CCCCCC',
    },
    datePickerContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        width: 360,
        alignSelf: 'center',
        marginTop: 20,
    },
    dateDropdown: {
        flex: 1,
        backgroundColor: '#fff',
        borderWidth: 2,
        borderColor: '#252525',
        borderRadius: 10,
        padding: 15,
        alignItems: 'center',
        justifyContent: 'center',
        minHeight: 50,
        flexDirection: 'row',
    },
    dateDropdownDay: {
        flex: 0.5,
        backgroundColor: '#fff',
        borderWidth: 2,
        borderColor: '#252525',
        borderRadius: 10,
        padding: 15,
        alignItems: 'center',
        justifyContent: 'center',
        minHeight: 50,
        flexDirection: 'row',
    },
    dateDropdownText: {
        fontSize: 18,
        fontFamily: fonts.regular,
        color: '#252525',
        textTransform: 'lowercase',
        flex: 1,
        textAlign: 'center',
    },
    dateDropdownTextPlaceholder: {
        color: '#999',
    },
    dateDropdownIcon: {
        marginLeft: 8,
    },
    ageErrorText: {
        color: '#FF5151',
        fontSize: 18,
        fontFamily: fonts.regular,
        marginTop: 12,
        textAlign: 'center',
        textTransform: 'lowercase',
    },
    modalOverlay: {
        flex: 1,
        justifyContent: 'flex-end',
    },
    modalOverlayAnimated: {
        flex: 1,
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
        justifyContent: 'flex-end',
    },
    modalContent: {
        backgroundColor: '#fff',
        borderTopLeftRadius: 20,
        borderTopRightRadius: 20,
        maxHeight: '70%',
        paddingBottom: 20,
    },
    modalTitle: {
        fontSize: 20,
        fontFamily: fonts.bold,
        color: '#252525',
        textAlign: 'center',
        padding: 20,
        borderBottomWidth: 1,
        borderBottomColor: '#E0E0E0',
        textTransform: 'lowercase',
    },
    modalScrollView: {
        maxHeight: 400,
    },
    modalItem: {
        padding: 20,
        borderBottomWidth: 1,
        borderBottomColor: '#F5F5F5',
    },
    modalItemSelected: {
        backgroundColor: '#F0F0F0',
    },
    modalItemText: {
        fontSize: 18,
        fontFamily: fonts.regular,
        color: '#333',
        textTransform: 'lowercase',
    },
    modalItemTextSelected: {
        fontFamily: fonts.bold,
        color: '#526EFF',
        textAlign: 'center',
    },
    // Slider styles
    sliderContainer: {
        width: 360,
        alignSelf: 'center',
        marginTop: 20,
    },
    sliderValue: {
        fontSize: 48,
        fontFamily: fonts.bold,
        color: '#526EFF',
        textAlign: 'center',
        marginBottom: 30,
    },
    sliderTrack: {
        height: 8,
        backgroundColor: '#F5F5F5',
        borderRadius: 4,
        position: 'relative',
        marginBottom: 10,
    },
    sliderThumb: {
        width: 24,
        height: 24,
        borderRadius: 12,
        backgroundColor: '#526EFF',
        borderWidth: 3,
        borderColor: '#252525',
        position: 'absolute',
        top: -8,
        left: '50%',
    },
    sliderLabels: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        paddingHorizontal: 10,
    },
    sliderLabel: {
        fontSize: 14,
        fontFamily: fonts.regular,
        color: '#666',
    },
    // Card styles
    cardContainer: {
        width: 360,
        alignSelf: 'center',
        flexDirection: 'row',
        flexWrap: 'wrap',
        justifyContent: 'space-between',
        gap: 12,
    },
    card: {
        flex: 1,
        minWidth: '30%',
        backgroundColor: '#F5F5F5',
        borderWidth: 2,
        borderColor: '#252525',
        borderRadius: 10,
        padding: 20,
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: 12,
    },
    cardSelected: {
        backgroundColor: '#526EFF',
        borderColor: '#252525',
    },
    cardText: {
        fontSize: 18,
        fontFamily: fonts.bold,
        color: '#333',
        textTransform: 'lowercase',
    },
    cardTextSelected: {
        color: '#fff',
    },
    // Sex card styles
    sexCardContainer: {
        width: 280,
        alignSelf: 'center',
        flexDirection: 'row',
        justifyContent: 'space-between',
        gap: 20,
        marginTop: 20,
    },
    sexCard: {
        width: 138,
        height: 138,
        backgroundColor: '#fff',
        borderWidth: 2,
        borderColor: '#252525',
        borderRadius: 12,
        padding: 16,
        alignItems: 'center',
        justifyContent: 'center',
        shadowColor: '#252525',
        shadowOffset: {
            width: 0,
            height: 4,
        },
        shadowOpacity: 1,
        shadowRadius: 0,
        elevation: 4,
        overflow: 'hidden',
    },
    sexCardIcon: {
        fontSize: 56,
        fontFamily: fonts.bold,
        marginBottom: 8,
        fontWeight: '900',
    },
    sexCardText: {
        fontSize: 16,
        fontFamily: fonts.bold,
        textTransform: 'lowercase',
    },
    // Goal card styles
    goalContainer: {
        width: 360,
        alignSelf: 'center',
        marginTop: 20,
    },
    goalRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginBottom: 12,
        gap: 12,
    },
    goalRowSingle: {
        flexDirection: 'row',
        justifyContent: 'center',
        marginBottom: 12,
    },
    goalCard: {
        width: 174, // (360 - 12) / 2 = 174 for two cards with gap
        height: 174, // Square
        backgroundColor: '#fff',
        borderWidth: 2,
        borderColor: '#252525',
        borderRadius: 12,
        padding: 16,
        alignItems: 'center',
        justifyContent: 'center',
        shadowColor: '#252525',
        shadowOffset: {
            width: 0,
            height: 4,
        },
        shadowOpacity: 1,
        shadowRadius: 0,
        elevation: 4,
        overflow: 'hidden',
    },
    goalCardSelected: {
        backgroundColor: '#526EFF',
    },
    goalIcon: {
        fontSize: 56,
        fontFamily: fonts.bold,
        marginBottom: 8,
        fontWeight: '900',
    },
    goalCardText: {
        fontSize: 16,
        fontFamily: fonts.bold,
        color: '#333',
        textTransform: 'lowercase',
        textAlign: 'center',
    },
    goalCardTextSelected: {
        color: '#fff',
    },
    // Activity card styles
    activityCardContainer: {
        width: 360,
        alignSelf: 'center',
        marginTop: 20,
    },
    activityCard: {
        width: '100%',
        backgroundColor: '#fff',
        borderWidth: 2,
        borderColor: '#252525',
        borderRadius: 12,
        padding: 20,
        marginBottom: 18,
        shadowColor: '#252525',
        shadowOffset: {
            width: 0,
            height: 4,
        },
        shadowOpacity: 1,
        shadowRadius: 0,
        elevation: 4,
        overflow: 'hidden',
    },
    activityCardSelected: {
        backgroundColor: '#526EFF',
    },
    activityCardTitle: {
        fontSize: 24,
        fontFamily: fonts.bold,
        color: '#252525',
        textTransform: 'lowercase',
        marginBottom: 8,
    },
    activityCardTitleSelected: {
        color: '#fff',
    },
    activityCardDesc: {
        fontSize: 16,
        fontFamily: fonts.regular,
        color: '#252525',
        textTransform: 'lowercase',
    },
    activityCardDescSelected: {
        color: '#fff',
    },
    // Frequency card styles
    frequencyCard: {
        width: '48%',
        backgroundColor: '#F5F5F5',
        borderWidth: 2,
        borderColor: '#252525',
        borderRadius: 10,
        padding: 20,
        alignItems: 'center',
        marginBottom: 12,
    },
    frequencyCardSelected: {
        backgroundColor: '#526EFF',
    },
    frequencyIcon: {
        fontSize: 40,
        marginBottom: 8,
    },
    frequencyCardText: {
        fontSize: 18,
        fontFamily: fonts.bold,
        color: '#333',
        textTransform: 'lowercase',
    },
    frequencyCardTextSelected: {
        color: '#fff',
    },
    // Diet card styles
    dietCardContainer: {
        width: 360,
        alignSelf: 'center',
        marginTop: 20,
        flexDirection: 'row',
        flexWrap: 'wrap',
        justifyContent: 'space-between',
        gap: 12,
    },
    dietCard: {
        width: 174, // (360 - 24) / 2 = 168, but using 174 to match goal cards
        height: 174, // Square
        backgroundColor: '#fff',
        borderWidth: 2,
        borderColor: '#252525',
        borderRadius: 12,
        padding: 16,
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: 12,
        shadowColor: '#252525',
        shadowOffset: {
            width: 0,
            height: 4,
        },
        shadowOpacity: 1,
        shadowRadius: 0,
        elevation: 4,
        overflow: 'hidden',
    },
    dietCardSelected: {
        backgroundColor: '#526EFF',
    },
    dietIcon: {
        fontSize: 56,
        fontFamily: fonts.bold,
        marginBottom: 8,
        fontWeight: '900',
    },
    dietCardText: {
        fontSize: 16,
        fontFamily: fonts.bold,
        color: '#333',
        textTransform: 'lowercase',
        textAlign: 'center',
    },
    dietCardTextSelected: {
        color: '#fff',
    },
    // Chip styles (for allergies)
    chipContainer: {
        width: 360,
        alignSelf: 'center',
        alignItems: 'center',
    },
    chipRow: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        justifyContent: 'center',
        gap: 10,
        marginBottom: 10,
        width: '100%',
    },
    chipRowBottom: {
        // No additional styling needed - justifyContent: 'center' from chipRow will center the 3 items
    },
    chip: {
        backgroundColor: '#F5F5F5',
        borderWidth: 2,
        borderColor: '#252525',
        borderRadius: 12,
        paddingHorizontal: 20,
        paddingVertical: 12,
        overflow: 'hidden',
    },
    chipSelected: {
        backgroundColor: '#526EFF',
    },
    chipText: {
        fontSize: 16,
        fontFamily: fonts.regular,
        color: '#252525',
        textTransform: 'lowercase',
    },
    chipTextSelected: {
        color: '#fff',
    },
    // Intensity card styles
    intensityCard: {
        width: '100%',
        backgroundColor: '#F5F5F5',
        borderWidth: 2,
        borderColor: '#252525',
        borderRadius: 10,
        padding: 24,
        marginBottom: 12,
    },
    intensityCardSelected: {
        backgroundColor: '#526EFF',
    },
    intensityCardTitle: {
        fontSize: 24,
        fontFamily: fonts.bold,
        color: '#333',
        textTransform: 'lowercase',
        marginBottom: 4,
    },
    intensityCardTitleSelected: {
        color: '#fff',
    },
    intensityCardDesc: {
        fontSize: 16,
        fontFamily: fonts.regular,
        color: '#666',
        textTransform: 'lowercase',
    },
    intensityCardDescSelected: {
        color: '#fff',
    },
    // Unit toggle styles
    unitToggle: {
        flexDirection: 'row',
        width: 360,
        alignSelf: 'center',
        backgroundColor: '#F5F5F5',
        borderRadius: 10,
        borderWidth: 2,
        borderColor: '#252525',
        padding: 4,
        marginBottom: 20,
        position: 'relative',
        overflow: 'hidden',
    },
    unitToggleBackground: {
        position: 'absolute',
        top: 4,
        bottom: 4,
        backgroundColor: '#526EFF',
        borderRadius: 8,
        borderWidth: 2,
        borderColor: '#252525',
    },
    unitButton: {
        flex: 1,
        paddingVertical: 12,
        alignItems: 'center',
        justifyContent: 'center',
        borderRadius: 8,
        backgroundColor: 'transparent',
        zIndex: 1,
    },
    unitButtonActive: {
        borderWidth: 2,
        borderColor: '#252525',
    },
    unitButtonText: {
        fontSize: 18,
        fontFamily: fonts.bold,
        color: '#333',
        textTransform: 'lowercase',
    },
    unitButtonTextActive: {
        color: '#fff',
    },
    unitSection: {
        width: 360,
        alignSelf: 'center',
        marginBottom: 24,
    },
    unitSectionTitle: {
        fontSize: 18,
        fontFamily: fonts.bold,
        color: '#333',
        marginBottom: 12,
        textTransform: 'lowercase',
    },
    // Purpose card styles
    purposeCard: {
        width: '48%',
        backgroundColor: '#F5F5F5',
        borderWidth: 2,
        borderColor: '#252525',
        borderRadius: 10,
        padding: 20,
        alignItems: 'center',
        marginBottom: 12,
    },
    purposeCardSelected: {
        backgroundColor: '#526EFF',
    },
    purposeIcon: {
        fontSize: 40,
        marginBottom: 8,
    },
    purposeCardText: {
        fontSize: 16,
        fontFamily: fonts.bold,
        color: '#333',
        textTransform: 'lowercase',
        textAlign: 'center',
    },
    purposeCardTextSelected: {
        color: '#fff',
    },
    // Macro card styles
    macroCard: {
        width: '100%',
        backgroundColor: '#F5F5F5',
        borderWidth: 2,
        borderColor: '#252525',
        borderRadius: 10,
        padding: 24,
        alignItems: 'center',
        marginBottom: 12,
    },
    macroCardSelected: {
        backgroundColor: '#526EFF',
    },
    macroCardTitle: {
        fontSize: 20,
        fontFamily: fonts.bold,
        color: '#333',
        textTransform: 'lowercase',
        marginTop: 12,
        marginBottom: 4,
    },
    macroCardTitleSelected: {
        color: '#fff',
    },
    macroCardDesc: {
        fontSize: 14,
        fontFamily: fonts.regular,
        color: '#666',
        textTransform: 'lowercase',
        textAlign: 'center',
    },
    macroCardDescSelected: {
        color: '#fff',
    },
    macroInputsContainer: {
        width: 360,
        alignSelf: 'center',
        marginTop: 20,
    },
    macroInputRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 12,
    },
    macroLabel: {
        fontSize: 16,
        fontFamily: fonts.bold,
        color: '#333',
        width: 120,
        textTransform: 'lowercase',
    },
    macroInputWrapper: {
        flex: 1,
    },
    macroInput: {
        borderWidth: 2,
        borderColor: '#252525',
        borderRadius: 10,
        backgroundColor: '#F5F5F5',
        paddingHorizontal: 15,
        paddingVertical: 12,
        fontSize: 18,
        fontFamily: fonts.regular,
        color: '#252525',
        minHeight: 50,
    },
    // Top back button
    topBackButton: {
        position: 'absolute',
        top: 20,
        left: 0, // Start from left edge
        flexDirection: 'row',
        alignItems: 'center',
        padding: 12,
        paddingLeft: 20, // Match button container paddingHorizontal
        zIndex: 10,
    },
    // Button container
    buttonContainer: {
        flexDirection: 'column',
        justifyContent: 'flex-end',
        alignItems: 'center',
        paddingTop: 20,
        paddingBottom: 30,
        width: '100%',
        paddingHorizontal: 20,
    },
    backButton: {
        flexDirection: 'row',
        alignItems: 'center',
        padding: 12,
    },
    backButtonText: {
        fontSize: 18,
        fontFamily: fonts.bold,
        color: '#526EFF',
        marginLeft: 4,
        textTransform: 'lowercase',
    },
    nextButton: {
        width: '100%',
        height: 50,
        marginTop: 15,
    },
});

